const {
  sequelize,
  Sequelize,
  ENUMS,
  User,
  ParticipationType,
  ParticipationTypeCountry,
  Country,
  Company,
  Accommodation,
  HotelRoom,
  HotelImages,
  Trip,
  Registration,
  Spouse,
  RegistrationTrip,
  File,
  RegistrationToken,
  Invoice,
  CompanyInvoice,
  AuditLog,
} = require('../models');

// Export sequelize instance and all models
module.exports = {
  sequelize,
  Sequelize,
  Op: Sequelize.Op,
  ENUMS,
  User,
  ParticipationType,
  ParticipationTypeCountry,
  Country,
  Company,
  Accommodation,
  HotelRoom,
  HotelImages,
  Trip,
  Registration,
  Spouse,
  RegistrationTrip,
  File,
  RegistrationToken,
  Invoice,
  CompanyInvoice,
  AuditLog,
};
