/* eslint-disable no-console */
/**
 * Migration: Create CompanyInvoiceRegistrations table
 *
 * Run with: NODE_ENV=development node scripts/createCompanyInvoiceRegistrations.js
 */
const { sequelize } = require('../models');

async function main() {
  console.log('Creating CompanyInvoiceRegistrations table...');

  try {
    await sequelize.authenticate();
    console.log('Database connection established.\n');

    await sequelize.query(`
      CREATE TABLE "CompanyInvoiceRegistrations" (
        "id"               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "companyInvoiceId" NUMBER NOT NULL REFERENCES "CompanyInvoices"("id"),
        "registrationId"   NUMBER NOT NULL REFERENCES "Registrations"("id"),
        "invoiceId"        NUMBER REFERENCES "Invoices"("id"),
        "totalJD"          NUMBER(12,2) DEFAULT 0,
        "totalUSD"         NUMBER(12,2) DEFAULT 0,
        "createdAt"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        "updatedAt"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
      )
    `);

    console.log('Table "CompanyInvoiceRegistrations" created successfully.');
  } catch (error) {
    if (
      error.message &&
      (error.message.includes('ORA-00955') ||
        error.message.includes('already exists') ||
        error.message.includes('name is already used'))
    ) {
      console.log('Table already exists, skipping creation.');
    } else {
      console.error('Error creating table:', error.message);
      process.exit(1);
    }
  } finally {
    await sequelize.close();
  }
}

main();
